library(shiny)
library(bslib)
library(dplyr)
library(tidyr)
library(purrr)
library(ggplot2)
library(readr)
library(lubridate)
library(DT)
library(htmltools)
library(scales)

get_app_dir <- function() {
  normalizePath(getwd(), winslash = "/", mustWork = TRUE)
}

app_dir <- get_app_dir()

source(file.path(app_dir, "R", "helpers.R"), local = TRUE)
source(file.path(app_dir, "R", "data.R"), local = TRUE)
source(file.path(app_dir, "R", "plots.R"), local = TRUE)
source(file.path(app_dir, "R", "components.R"), local = TRUE)
source(file.path(app_dir, "R", "ui_theme.R"), local = TRUE)
source(file.path(app_dir, "R", "ui_overview.R"), local = TRUE)
source(file.path(app_dir, "R", "ui_recovery.R"), local = TRUE)
source(file.path(app_dir, "R", "ui_timeseries.R"), local = TRUE)
source(file.path(app_dir, "R", "ui_seasonal.R"), local = TRUE)
source(file.path(app_dir, "R", "ui_methods.R"), local = TRUE)
source(file.path(app_dir, "R", "ui.R"), local = TRUE)
source(file.path(app_dir, "R", "server_overview.R"), local = TRUE)
source(file.path(app_dir, "R", "server_recovery_helpers.R"), local = TRUE)
source(file.path(app_dir, "R", "server_recovery.R"), local = TRUE)
source(file.path(app_dir, "R", "server_seasonal_helpers.R"), local = TRUE)
source(file.path(app_dir, "R", "server_seasonal.R"), local = TRUE)
source(file.path(app_dir, "R", "server_timeseries.R"), local = TRUE)
source(file.path(app_dir, "R", "server_methods.R"), local = TRUE)
source(file.path(app_dir, "R", "server.R"), local = TRUE)
