#!/bin/bash
# ==============================================================================
# Figure Renumbering for npj Digital Medicine Submission
# ==============================================================================
# Mapping:
#   NEW Fig 1 = Framework architecture diagram (fig1_framework.R output)
#   NEW Fig 2 = Model selection heatmap      (OLD fig1)
#   NEW Fig 3 = Recovery trajectories         (OLD fig2)
#   NEW Fig 4 = Seasonal analysis             (OLD fig3_a + fig3_b)
#   NEW Fig 5 = Dashboard screenshots         (fig5_dashboard.R output)
#
# Demoted to Supplementary:
#   OLD fig4 (suppression/rebound) → Supplementary Fig S_suppression
#   OLD fig5 (Cox forest plots)    → Supplementary Fig S_cox
# ==============================================================================

cd ../Outcome/Publish

# Create submit directory if not exists
mkdir -p submit

echo "=== Copying figures for submission ==="

# NEW Fig 1: Framework architecture (generated by fig1_framework.R)
if [ -f fig1_framework.pdf ]; then
  cp fig1_framework.pdf submit/Figure1.pdf
  cp fig1_framework.png submit/Figure1.png
  echo "  Fig 1 (Framework) -> submit/Figure1.pdf"
else
  echo "  WARNING: fig1_framework.pdf not found. Run fig1_framework.R first."
fi

# NEW Fig 2: Model selection heatmap (was OLD fig1)
if [ -f fig1.pdf ]; then
  cp fig1.pdf submit/Figure2.pdf
  cp fig1.png submit/Figure2.png
  echo "  Fig 2 (Model selection) -> submit/Figure2.pdf"
fi

# NEW Fig 3: Recovery trajectories (was OLD fig2)
if [ -f fig2.pdf ]; then
  cp fig2.pdf submit/Figure3.pdf
  cp fig2.png submit/Figure3.png
  echo "  Fig 3 (Recovery trajectories) -> submit/Figure3.pdf"
fi

# NEW Fig 4: Seasonal analysis (was OLD fig3)
if [ -f fig3_a.pdf ]; then
  cp fig3_a.pdf submit/Figure4a.pdf
  cp fig3_a.png submit/Figure4a.png
  echo "  Fig 4a (IRR heatmaps) -> submit/Figure4a.pdf"
fi
if [ -f fig3_b.pdf ]; then
  cp fig3_b.pdf submit/Figure4b.pdf
  cp fig3_b.png submit/Figure4b.png
  echo "  Fig 4b (Seasonal radar) -> submit/Figure4b.pdf"
fi

# NEW Fig 5: Dashboard screenshots
if [ -f fig5_dashboard.pdf ]; then
  cp fig5_dashboard.pdf submit/Figure5.pdf
  cp fig5_dashboard.png submit/Figure5.png
  echo "  Fig 5 (Dashboard) -> submit/Figure5.pdf"
else
  echo "  WARNING: fig5_dashboard.pdf not found. Run fig5_dashboard.R first."
fi

# Demoted figures -> Supplementary
if [ -f fig4.pdf ]; then
  cp fig4.pdf submit/FigureS_suppression.pdf
  cp fig4.png submit/FigureS_suppression.png
  echo "  Supplementary: Fig S suppression -> submit/FigureS_suppression.pdf"
fi
if [ -f fig5.pdf ]; then
  cp fig5.pdf submit/FigureS_cox.pdf
  cp fig5.png submit/FigureS_cox.png
  echo "  Supplementary: Fig S cox -> submit/FigureS_cox.pdf"
fi

echo ""
echo "=== Figure renumbering complete ==="
echo "Submit directory contents:"
ls -la submit/
